extensions:

  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
  nragent:
    tls:
      cert_file: "./LocalOTelCollectorTesting.cert"
      key_file: "./LocalOTelCollectorTesting.key"

exporters:
  logging:  
  otlp:
    endpoint: otlp.nr-data.net:443
    headers:
      api-key: "api-key"

service:
  pipelines:
    traces:
      receivers: [otlp, nragent]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp, nragent]
      exporters: [logging, otlp]
  extensions: [zpages]
#  extensions: [pprof, zpages]
